apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hash
spec:
  selector:
    matchLabels:
      app: node-hash
  template:
    metadata:
      labels:
        app: node-hash
    spec:
      containers:
        - name: node-hash
          image: pedr0aroucha/node-hash
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "80"
          resources:
            limits:
              memory: "64Mi"
              cpu: "128m"
          ports:
            - containerPort: 80
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: node-hash
spec:
  selector:
    app: node-hash
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
